# Generated by Django 3.1.2 on 2020-10-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='funas',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombrefunado', models.CharField(help_text='Ingrese nombre del funado', max_length=200)),
                ('des', models.TextField(help_text='Descripcion de la funa', max_length=1000)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
